### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by frankrousseau** [MrFrangipane/docgen#1]
Hello @MrFrangipane,

  Thank you for this module! I noticed some issues I share with you here:

* Sometimes the parameter is not found and it is replaced by `*args, **kwargs`. 
* Empty parameter functions are replaced by `*args, **kwargs`.
* It includes the documentation of decorator functions I use.
* I'm not convinced by your layout for function signatures. But I don't have something good to propose except the idea of using the `def_list` markdown extension.

PS: My goal is to use it to build the [Gazu documentation](https://gazu.cg-wire.com).

**Comment by MrFrangipane** [comment]
Hello @frankrousseau 
Thank you for taking the time to write some feedback !
- Do you have examples of the situations you describe ?
- This decorator / imported classes issue is known, I have to check it out
- When you say 'fonction signatures' you mean how it's converted to markdown, or how it's written in the docstrings ?

**Comment by MrFrangipane** [comment]
v1.3.2 should fix the decorator issue

https://pypi.python.org/pypi/frangidoc
