### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by Lawouach** [MrFrangipane/docgen#3]
I was wondering if there was plan for Python 3 support?

Maybe some type annotation as well?

**Comment by MrFrangipane** [comment]
Hi, 
Thank you for your interest in that package !  
Python 3 support is a good idea. I will definitly look into it when possible

btw, issue #2 must be due the relative python2 imports

**Comment by Lawouach** [comment]
Yeah, that would make sense indeed. Cheers

**Comment by MrFrangipane** [comment]
Version 1.4.0 should support Python3
